# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mauricio Serna
tagline:          'Autodidact, nerd'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mauricio Serna'
  url:            https://twitter.com/fmauricios

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fmauricios/mauricio
