# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mauricio Serna
tagline:          'Autodidact, nerd'
description:      'Blockchain | Nodejs | Elixir 🚀'
url:              http://mauricioserna.me
baseurl:          /

author:
  name:           'Mauricio Serna'
  url:            https://twitter.com/fmauricios

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fmauricios/

linkedin:
  url:            https://www.linkedin.com/in/mauricio-serna-fl%C3%B3rez-3a8516ab/

cv:
  url:            https://s3-us-west-2.amazonaws.com/mauricioserna/static/documents/cv.pdf

excerpt_separator: "\n\n"
